### ISSUE TITLE
Don't install tests

### ISSUE THREAD

**Issue by schra** [sympy/sphinx-math-dollar#17]
I packaged this repo for the Arch User Repository (https://github.com/schra/pkgbuilds/blob/master/python-sphinx-math-dollar/PKGBUILD) and I noticed that the tests are also installed when calling `setup.py`.

It would be better if the tests weren't installed. I think this issue would already be fixed by moving the `tests/` folder out of the `sphinx_math_dollar/` folder and put it directly in the root directory instead?

**Comment by asmeurer** [comment]
The tests are included with the package intentionally. 

(thanks for packaging the package for Arch btw)
