### ISSUE TITLE
Support recommonmark

### ISSUE THREAD

**Issue by asmeurer** [sympy/sphinx-math-dollar#19]
I tried using this with recommonmark and it doesn't seem to work. That is unfortunate because recommonmark has some odd syntax for math (https://recommonmark.readthedocs.io/en/latest/auto_structify.html#math-formula). 

Alternately, get recommonmark to support the normal dollar syntax.

**Comment by asmeurer** [comment]
It looks like Text nodes get split across backslashes. But it works if you set `visit_paragraph = visit_Text`, at least for math in paragraphs.

**Comment by asmeurer** [comment]
Except doing that causes it to match too much, like math inside of backticks. I guess that would be a problem even for markdown.

**Comment by asmeurer** [comment]
[Myst](https://myst-parser.readthedocs.io/en/latest/index.html) supports the usual dollar and double dollar math, and seems to be nicer than recommonmark in general. So I would just recommend anyone using recommonmark who wants normal dollar math to switch to Myst.

**Comment by MingjieJian** [comment]
> [Myst](https://myst-parser.readthedocs.io/en/latest/index.html) supports the usual dollar and double dollar math, and seems to be nicer than recommonmark in general. So I would just recommend anyone using recommonmark who wants normal dollar math to switch to Myst.

I have tried many settings in recommonmark and Myst is easier when it comes to markdown  + $$ math.

**Comment by asmeurer** [comment]
Recommonmark is now a dead project, and MyST supports dollar math out of the box.
