### ISSUE TITLE
Using "node.rawsource" is not safe and deprecated.

### ISSUE THREAD

**Issue by gmilde** [sympy/sphinx-math-dollar#22]
The "rawsource" exists only for information and debugging purposes.
* It is not guaranteed to be accurate and may be empty.
* It will be left empty for Text nodes in Docutils > 0.17 and finally be removed from `nodes.Text` (see "Future changes" in docutils/RELEASE-NOTES).

Docutils stores "null-escaped" text in Text nodes since version 0.16 (2020-01-12), so there is
no additional information in the rawsource.

Instead of ``node.rawsource``, use ``unicode(node).replace('\x00', '\\')``
or ``nodes.unescape(unicode(node), restore_backslashes=True)``.

**Comment by asmeurer** [comment]
Any reason to not just make `rawsource` give this?

**Comment by gmilde** [comment]
Short answer: it does not work.

Long answer: When trying to fix escaping in the "smartquotes" transform
(triggered by https://sourceforge.net/p/docutils/bugs/332/), the first
attempt used the "rawsource" attribute. Adding "rawsource" to text nodes
could not be completed in a clean manner and ongoing discussion confirmed
"rawsource"

  > was only meant for testing during development, not for formal
  production use. That's why it's incomplete and untested.
  
  -- https://sourceforge.net/p/docutils/mailman/message/36119259/

The alternative¹, allowed to solve the smartquotes escaping problem as
well as https://sourceforge.net/p/docutils/bugs/353/.

¹ Keep null-escaped text in doctree, unescape in node.astext().
  This is d) in https://sourceforge.net/p/docutils/mailman/message/36155246/

With ``nodes.Text.data`` now holding the full information, there is no need to
duplicate this in ``nodes.Text.rawsource``.

Changing 

      - split_dollars(node.rawsource)
      + split_dollars(unicode(node).replace('\x00', '\\'))

 in sphinx_math_dollar/extension.py should make "math-dollar" future-proof and also
solve the issue with  priority in ``extension.TransformMath``:

      # [...] We want it
      # to apply before things that change rawsource, since we have to use that
      # to get the version of the text with backslashes.

**Comment by asmeurer** [comment]
Ok.

I'm unclear about your suggested fix. Is there any semantic difference between `unicode(node).replace('\x00', '\\')` and `nodes.unescape(unicode(node), restore_backslashes=True)` or is one just a shorthand for the other? 

> solve the issue with priority in extension.TransformMath:

We actually have deeper priority issues #16. I don't know if this would do anything about that. It seems to me we would need to preprocess the whole source before docutils to fix that issue (but I'm hopeful that that isn't the case and there is a simpler solution).

**Comment by gmilde** [comment]
> I'm unclear about your suggested fix. Is there any semantic difference
> between unicode(node).replace('\x00', '\\') and
> nodes.unescape(unicode(node), restore_backslashes=True) or is one just
> a shorthand for the other?

A very subtle one: The latter leaves the specification of the actual
escape character to Docutils. However, chances that Docutils will change
the escape character from '\x00' to something else are rather small.

For subsequent transforms, it is important to make sure to revert the
escape-character replacement for the text part in nodes with mixed
content, e.g. transforms.universal.SmartQuotes will be affected when escapes
are removed or changed by MathDollarReplaces.

Example:

     This is a paragraph with $3$ parts \--- text, math, text.
     
should give the same result as     

     This is a paragraph with :math`3` parts \--- text, math, text.
     
The escaped "mdash" ASCII shorthand should not be converted to a literal
mdash character by SmartQuotes.

>     solve the issue with priority in extension.TransformMath:

> We actually have deeper priority issues #16. I don't know if this would do
> anything about that. It seems to me we would need to preprocess the whole
> source before docutils to fix that issue (but I'm hopeful that that isn't the
> case and there is a simpler solution).

I am afraid there is no simple solution. Everything inside the dollars is
parsed as rST and hence needs to be valid "stock" rST. 

Changing the rST parser is not supported by an API. The idea is to keep the
core syntax stable and provide extension mechanisms (roles for inline
elements and directives for block level elements.
