### ISSUE TITLE
Update versioneer

### ISSUE THREAD

**Issue by jamesjer** [sympy/sphinx-math-dollar#27]
The version of versioneer.py included in the 1.2 release uses SafeConfigParser, which was deprecated in python 3.2 and has been removed entirely from the upcoming python 3.11.  This has been fixed in recent versions of versioneer.  Please update to a more recent version of versioneer.py.  (This was discovered while doing test builds of all Fedora packages with the current alpha version of python 3.11, by the way.)

**Comment by oscargus** [comment]
Thanks for notifying! I made an attempt to update it and it seems to pass the tests on 3.11 now. 

(Bad idea to force push a commit with an issue number in the message...)

**Comment by jamesjer** [comment]
Great!  Thank you for the fast response.
