### ISSUE TITLE
Add support for display math (double dollar signs)

### ISSUE THREAD

**Issue by asmeurer** [sympy/sphinx-math-dollar#4]
I think we just need to detect $$math$$ and add a math_block node. I don't know if math_block is allowed anywhere, so it might be harder.

**Comment by jksuom** [comment]
I have been experimenting with TeX's method: sequential scanning and dollars as mode shift. The following seems to work also with single-line $$...$$.
```
def process_dollars(app, docname, source):
    s = '\n'.join(source)
    if '$' not in s:
        return
    # Escape `\$` for splitting.
    parts = s.replace('\\$', '\00').split('$')
    parts = [part.replace('\00', '\\$') for part in parts]

    s = ''
    # mode: nr of dollars at start
    # text = 0, math = 1, display = 2
    mode = 0
    while parts:
        part = parts.pop(0)
        if mode == 2 and parts and not parts[0]:
            # $$ at end
            if part:
                s += '\n\n.. math:: ' + part + '\n\n'
            del parts[0]  # empty
            mode = 0
        elif mode > 0 and parts:
            # $ at end
            if part:
                s += ':math:`' + part + '`'
            mode = 0
        else:
            if part:
                s += part
            mode = 1  # not true if there are no parts left, but then in does not matter
            if parts and not parts[0]:
                del parts[0]
                mode = 2

    source[:] = s.split('\n')
```
Unbalanced expressions like $$...$ are silently treated as inline math instead of interrupting the execution as TeX does:
> Missing $ inserted.
I've inserted a begin-math/end-math symbol since I think you left one out. Proceed, with fingers crossed.

The unexpected output should alert the user.

**Comment by asmeurer** [comment]
We should probably switch to something that works more like a parser. The current regex in this code is already quite complicated of the backreferences to guard against escaped dollars and nested dollars. I don't know how easy it would be to generalize to double dollars, and making it work for general delimiters would be quite difficult. 

Note that `process_dollars` is now `split_dollars`, which should work quite well for this style. https://github.com/sympy/sphinx-math-dollar/blob/master/sphinx_math_dollar/math_dollar.py

**Comment by asmeurer** [comment]
By the way I think the current parser is not really correct with the way it handles escapes. It won't do the right thing with an escaped backslash before a dollar `$\\$`. This probably wouldn't happen in any real application, but it would be nice to use a lexer that handles backslash escaping automatically.

**Comment by asmeurer** [comment]
> The unexpected output should alert the user.

Currently something like `$\sin(x)` with an unclosed dollar is parsed as text. But maybe an error would be better, and we should require unmatched dollars to be escaped to appear as literal dollars. I'm not sure.
